name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - release/*
      - hotfix/*
  pull_request:
    branches-ignore:
      - tag/*

jobs:
  test-matrix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 17, 18-ea, 19-ea ]
        os: [ ubuntu-20.04, windows-2022 ]
        architecture: [ x64, x86 ]
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }} ${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          architecture: ${{ matrix.architecture }}
      - name: Set up Maven 3.8.4
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: 3.8.4
      - name: Build with Maven
        run: mvn -X clean install